image: electronuserland/builder:wine

stages:
  - install
  - pack-linux

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: install
  script:
    - npm install

pack_linux:
  stage: pack-linux
  only:
    - main
  script:
    - npm run pack-linux
  artifacts:
    paths:
      - dist/
